### ISSUE TITLE
Depreciated whitelist_externals

### ISSUE THREAD

**Issue by andyatterton** [renalreg/ukrdc-sqla#83]
Something to be aware of, whitelist_externals is depreciated and has been replaced with allowlist_externals. In my scenario, I simply change out one for the other and everything worked, but no idea if this is running some older version of tox for some reason. Link to the notes

https://tox.wiki/en/latest/changelog.html#bugfixes-4-0-0rc4

**Comment by jtc42** [comment]
Resolved by https://github.com/renalreg/ukrdc-sqla/pull/81
